project_root = "/home/rpnerd/Desktop/ACE-Step-1.5"
config_path = "acestep-v15-turbo"
checkpoint_dir = "/home/rpnerd/Desktop/ACE-Step-1.5/checkpoints"
lm_model_path = "acestep-5Hz-lm-1.7B"
backend = "vllm"
device = "auto"
offload_to_cpu = true
offload_dit_to_cpu = false
save_dir = "output"
audio_format = "flac"
caption = "XXXTentacion singing 'Counting Stars' by OneRepublic, pop, emo-rap"
prompt = ""
lyrics = "/home/rpnerd/Desktop/ACE-Step-1.5/lyrics.txt"
duration = -1.0
instrumental = false
keyscale = ""
timesignature = ""
vocal_language = "en"
task_type = "text2music"
instruction = "Fill the audio semantic mask based on the given conditions:"
repainting_start = 0.0
repainting_end = -1
audio_cover_strength = 1.0
lego_track = ""
extract_track = ""
complete_tracks = ""
sample_mode = false
sample_query = ""
use_format = false
inference_steps = 8
seed = -1
guidance_scale = 7.0
use_adg = false
shift = 3.0
infer_method = "ode"
thinking = true
lm_temperature = 0.85
lm_cfg_scale = 2.0
lm_top_k = 0
lm_top_p = 0.9
use_cot_metas = true
use_cot_caption = true
use_cot_lyrics = false
use_cot_language = true
use_constrained_decoding = true
batch_size = 1
use_random_seed = true
allow_lm_batch = false
lm_batch_chunk_size = 8
constrained_decoding_debug = false
audio_codes = ""
cfg_interval_start = 0.0
cfg_interval_end = 1.0
lm_negative_prompt = "NO USER INPUT"
log_level = "INFO"
